### ISSUE TITLE
Bot Replies in private instead of group 

### ISSUE THREAD

**Issue by whale2186** [woiza/telegram-bot-radarr#18]
when I type commands like /id it displays in gorup but if I use commands like /q or /library it displays in  private.

**Comment by woiza** [comment]
How can I reproduce this? Should all messages end up in private or group chats?

**Comment by whale2186** [comment]
> How can I reproduce this? Should all messages end up in private or group chats?

Can you make it a option to reply in group using chat id maybe ?

**Comment by woiza** [comment]
Good Idea, I will try that next week (busy/traveling until Sunday).

**Comment by whale2186** [comment]
> Good Idea, I will try that next week (busy/traveling until Sunday).

Great Project tho :)
