### ISSUE TITLE
BUTTON_DATA_INVALID

### ISSUE THREAD

**Issue by smashkins** [woiza/telegram-bot-radarr#21]
during the selection of the quality profile the bot does not move forward. In the logs the message says:
Error editing message with keyboard: Bad Request: BUTTON_DATA_INVALID
Error sending message: Bad Request: BUTTON_DATA_INVALID

I have a custom quality profile on radarr

**Comment by woiza** [comment]
What's the name of the profile? Please provide the exact string since I can't reproduce it.

**Comment by woiza** [comment]
How many profiles do you have?

**Comment by smashkins** [comment]
The name of the profile is "HD - 720p/1080p" with language releases in italian language.
I have 7 profiles.
If there is a way to perform a debug that could help you solve the error, tell me where I should look. Thank you.

**Comment by woiza** [comment]
I can't reproduce it and the bot moves forward if I select any of the following:

<img width="334" alt="Screenshot 2024-08-28 at 08 20 06" src="https://github.com/user-attachments/assets/7b3553c1-1a76-4522-8bb1-82aaf1e1c21c">

However, I just remembered that I use profile IDs and not names...

Here is how I get all profiles from Radarr:
[get profiles](https://github.com/woiza/telegram-bot-radarr/blob/develop/pkg/bot/add.go#L246)

Create a list of profiles for the bot:
[show profiles](https://github.com/woiza/telegram-bot-radarr/blob/develop/pkg/bot/add.go#L291)
I think this is where it fails for you.

Get profile ID from callback / user selection:
[callback data](https://github.com/woiza/telegram-bot-radarr/blob/develop/pkg/bot/add.go#L321)

What Radarr version do you use? Could you please update it to the latest?

**Comment by smashkins** [comment]
```
{
 "appData": "/config",
 "appName": "Radarr",
 "authentication": "forms",
 "branch": "master",
 "buildTime": "2024-08-20T17:49:34Z",
 "databaseType": "sqLite",
 "databaseVersion": "3.45.3",
 "instanceName": "Radarr",
 "isAdmin": false,
 "isDebug": false,
 "isDocker": true,
 "isLinux": true,
 "isNetCore": true,
 "isOsx": false,
 "isProduction": true,
 "isUserInteractive": true,
 "isWindows": false,
 "migrationVersion": 237,
 "mode": "console",
 "osName": "alpine",
 "packageAuthor": "[linuxserver.io](https://linuxserver.io)",
 "packageUpdateMechanism": "docker",
 "packageVersion": "5.9.1.9070-ls234",
 "runtimeName": "netcore",
 "runtimeVersion": "6.0.32",
 "startTime": "2024-08-23T16:30:53Z",
 "startupPath": "/app/radarr/bin",
 "urlBase": "",
 "version": "5.9.1.9070"
}
```

Is there any debug mode for bot ?

**Comment by woiza** [comment]
Unfortunately not. You could clone the repo and add print statements to the code sections mentioned above. 
Alternatively, I could try to reproduce it with all of your profiles.

**Comment by smashkins** [comment]
I cloned the repo and added some print statements.

```
// fmt.Println("Quality Profiles:")
//	for _, profile := range profiles {
//		fmt.Printf("ID: %d, Name: %s\n", profile.ID, profile.Name)
//	}

Quality Profiles:
ID: 1, Name: Any
ID: 2, Name: SD
ID: 3, Name: HD-720p
ID: 4, Name: HD-1080p
ID: 5, Name: Ultra-HD
ID: 6, Name: HD - 720p/1080p
ID: 7, Name: HD - 720p/1080p - Eng
```

On the callback any buttonInline pressed produces

`profileIDStr: 6`

```
Error sending message: Bad Request: BUTTON_DATA_INVALID
Error editing message with keyboard: Bad Request: BUTTON_DATA_INVALID
```

`profileIDStr: 1`

```
Error sending message: Bad Request: BUTTON_DATA_INVALID
Error editing message with keyboard: Bad Request: BUTTON_DATA_INVALID
```

I'm trying to understand why

**Comment by smashkins** [comment]
ok you can close it and I apologize. While debugging, I noticed that the bot was encountering an error in the method that listed the root folders. An incorrect root folder (a path to a folder with spaces) had been added to my Radarr instance, and the bot was likely failing because of that. Anyway, after removing the incorrect root folder, the bot works normally. Thank you!

**Comment by woiza** [comment]
@smashkins I tested the bot with a root folder containing spaces and `(` `)`. I think the path of your root folder was too long.  As far as I know button data is limited to 64 bytes.

**Comment by smashkins** [comment]
Exactly!

**Comment by woiza** [comment]
@smashkins check out the new release and please let me know what you think. I will update the sonarr bot afterwards.

**Comment by smashkins** [comment]
Great! It seems like a better solution to use the root folder ID instead of the path string! In the end, this whole discussion was worth something 😄

**Comment by woiza** [comment]
Definitely, thanks for pointing this out. I totally overlooked the root folder ID when I initially developed the bot.
