### ISSUE TITLE
Some tips

### ISSUE THREAD

**Issue by smashkins** [woiza/telegram-bot-radarr#3]
Great bot! Thnx!
Some tips:
- add a command to search a specific monitored movie instead to searches all monitored movies?
- add a command to list all monitored movies
- add a command to unmonitor a movie

**Comment by woiza** [comment]
@smashkins good ideas, thank you.

**Comment by woiza** [comment]
@smashkins check out the new release. /start will list the new and updated commands. Let me know what you think.

**Comment by woiza** [comment]
resolved with latest release
